"""
GreenInfer Complexity Classifier Training Script
Trains a lightweight DistilBERT classifier to predict prompt complexity.

This is the ML version of the complexity scorer.
The rule-based scorer in complexity_scorer.py works well already,
but training a classifier gives you:
  - Better generalization to unusual prompts
  - A real trained model artifact to show in your repo
  - Something you can fine-tune as you collect real usage data

Dataset: you can use the synthetic dataset generated by build_complexity_dataset.py
or label real prompts from your chatbot logs over time.

Usage:
    python train_complexity.py
    
    # After training, the model is saved to models/complexity_classifier/
    # Upload it to Hugging Face and reference it in your backend
"""

import json
import os
import random
from dataclasses import dataclass
from typing import Optional

import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from transformers import (
    DistilBertTokenizer,
    DistilBertForSequenceClassification,
    get_linear_schedule_with_warmup,
    AdamW,
)
from sklearn.metrics import mean_absolute_error, r2_score
import numpy as np

# ── Config ──────────────────────────────────────────────────────────────────

SAVE_PATH       = "models/complexity_classifier"
DATA_PATH       = "data/complexity_dataset.json"
MODEL_BASE      = "distilbert-base-uncased"

EPOCHS          = 20
BATCH_SIZE      = 16
LR              = 2e-5
MAX_LEN         = 128
TRAIN_SPLIT     = 0.85
SEED            = 42

NUM_LABELS      = 4  # Low, Medium, High, Very High (classification)
# Set to 1 if you want regression (predict continuous 0-1 score instead)
REGRESSION_MODE = False

random.seed(SEED)
torch.manual_seed(SEED)


# ── Dataset ──────────────────────────────────────────────────────────────────

class ComplexityDataset(Dataset):
    def __init__(self, examples: list, tokenizer, max_len: int):
        self.examples  = examples
        self.tokenizer = tokenizer
        self.max_len   = max_len

        self.label_map = {"Low": 0, "Medium": 1, "High": 2, "Very High": 3}

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        item   = self.examples[idx]
        prompt = item["prompt"]
        label  = self.label_map[item["label"]] if not REGRESSION_MODE else item["score"]

        encoding = self.tokenizer(
            prompt,
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt"
        )
        return {
            "input_ids":      encoding["input_ids"].squeeze(),
            "attention_mask": encoding["attention_mask"].squeeze(),
            "label":          torch.tensor(label, dtype=torch.long if not REGRESSION_MODE else torch.float),
        }


# ── Training ─────────────────────────────────────────────────────────────────

def train():
    print("=" * 65)
    print("GreenInfer Complexity Classifier Training")
    print("=" * 65)

    # Load dataset
    if not os.path.exists(DATA_PATH):
        print(f"Dataset not found at {DATA_PATH}")
        print("Run: python build_complexity_dataset.py first")
        return

    with open(DATA_PATH) as f:
        examples = json.load(f)

    print(f"Loaded {len(examples)} examples")

    # Split
    random.shuffle(examples)
    split = int(len(examples) * TRAIN_SPLIT)
    train_data = examples[:split]
    val_data   = examples[split:]
    print(f"Train: {len(train_data)} | Val: {len(val_data)}")

    # Tokenizer and model
    tokenizer = DistilBertTokenizer.from_pretrained(MODEL_BASE)
    if REGRESSION_MODE:
        model = DistilBertForSequenceClassification.from_pretrained(
            MODEL_BASE, num_labels=1
        )
    else:
        model = DistilBertForSequenceClassification.from_pretrained(
            MODEL_BASE, num_labels=NUM_LABELS
        )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")
    model.to(device)

    # Datasets and loaders
    train_ds = ComplexityDataset(train_data, tokenizer, MAX_LEN)
    val_ds   = ComplexityDataset(val_data,   tokenizer, MAX_LEN)
    train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
    val_dl   = DataLoader(val_ds,   batch_size=BATCH_SIZE)

    # Optimizer and scheduler
    optimizer = AdamW(model.parameters(), lr=LR, weight_decay=0.01)
    total_steps = len(train_dl) * EPOCHS
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=int(total_steps * 0.1),
        num_training_steps=total_steps
    )

    if REGRESSION_MODE:
        loss_fn = nn.MSELoss()
    else:
        loss_fn = nn.CrossEntropyLoss()

    best_val_loss = float("inf")
    print("\nStarting training...\n")
    print(f"{'Epoch':<6} {'Train Loss':<12} {'Val Loss':<12} {'Val Acc':<10}")
    print("-" * 44)

    for epoch in range(1, EPOCHS + 1):
        # Train
        model.train()
        train_losses = []
        for batch in train_dl:
            input_ids   = batch["input_ids"].to(device)
            attn_mask   = batch["attention_mask"].to(device)
            labels      = batch["label"].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attn_mask)
            logits  = outputs.logits

            if REGRESSION_MODE:
                loss = loss_fn(logits.squeeze(), labels.float())
            else:
                loss = loss_fn(logits, labels)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()
            optimizer.zero_grad()
            train_losses.append(loss.item())

        # Validate
        model.eval()
        val_losses, correct, total = [], 0, 0
        with torch.no_grad():
            for batch in val_dl:
                input_ids = batch["input_ids"].to(device)
                attn_mask = batch["attention_mask"].to(device)
                labels    = batch["label"].to(device)

                outputs = model(input_ids=input_ids, attention_mask=attn_mask)
                logits  = outputs.logits

                if REGRESSION_MODE:
                    loss = loss_fn(logits.squeeze(), labels.float())
                else:
                    loss = loss_fn(logits, labels)
                    preds = logits.argmax(dim=1)
                    correct += (preds == labels).sum().item()
                    total   += labels.size(0)

                val_losses.append(loss.item())

        avg_train = sum(train_losses) / len(train_losses)
        avg_val   = sum(val_losses)   / len(val_losses)
        acc_str   = f"{correct/total*100:.1f}%" if not REGRESSION_MODE else "N/A"

        print(f"{epoch:<6} {avg_train:<12.4f} {avg_val:<12.4f} {acc_str:<10}")

        if avg_val < best_val_loss:
            best_val_loss = avg_val
            os.makedirs(SAVE_PATH, exist_ok=True)
            model.save_pretrained(SAVE_PATH)
            tokenizer.save_pretrained(SAVE_PATH)
            print(f"       -> Saved best model (val_loss={avg_val:.4f})")

    print(f"\nTraining complete. Best val loss: {best_val_loss:.4f}")
    print(f"Model saved to: {SAVE_PATH}")
    print("\nTo upload to Hugging Face:")
    print(f"  huggingface-cli upload YOUR_USERNAME/greeninfer-complexity {SAVE_PATH}")


if __name__ == "__main__":
    train()
